name: Azure Deployment

on:
  workflow_dispatch:
  push:
    branches:
    - hg
  pull_request:
    branches:
    - hg

permissions:
  id-token: write
  contents: read

env:
  AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}

jobs:
  build-test:
    name: Build and Test

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set .NET SDK version
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x

    - name: Package restore
      shell: bash
      run: |
        dotnet restore

    - name: Build
      shell: bash
      run: |
        dotnet build -c Release --no-restore --verbosity normal

    - name: Test
      shell: bash
      run: |
        dotnet test -c Release --filter:"TestCategory!=Integration" --no-build --verbosity normal

    - name: Publish artifact
      shell: bash
      run: |
        dotnet publish src/nt-mms/NhnToast.Mms.csproj -c Release

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: nt-mms
        path: src/nt-mms/bin/Release/net6.0/publish

  deploy-dev:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    name: Deploy to Dev

    needs:
    - build-test

    runs-on: ubuntu-latest

    environment: dev

    env:
      AZURE_RESOURCE_GROUP: "rg-${{ vars.AZURE_ENV_NAME }}-${{ vars.AZURE_ENV_INFRA }}-${{ vars.AZURE_LOCATION_CODE }}"
      AZURE_APIM_NAME: "apim-${{ vars.AZURE_ENV_NAME }}-${{ vars.AZURE_ENV_INFRA }}-${{ vars.AZURE_LOCATION_CODE }}"
      AZURE_FUNCTION_APP_NAME: "fncapp-${{ vars.AZURE_ENV_NAME }}-mms-${{ vars.AZURE_ENV_INFRA }}-${{ vars.AZURE_LOCATION_CODE }}"

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: nt-mms
        path: artifact/nt-mms

    - name: Zip artifact
      shell: bash
      run: |
        pushd artifact/nt-mms
        zip -r fncapp.zip .
        popd

        mv artifact/nt-mms/fncapp.zip artifact/fncapp.zip

    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ env.AZURE_CLIENT_ID }}
        tenant-id: ${{ env.AZURE_TENANT_ID }}
        subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}        

    - name: Deploy artifact
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_FUNCTION_APP_NAME }}
        package: artifact/fncapp.zip

    - name: Update APIM named value with function key
      shell: bash
      run: |
        functionKey=$(az functionapp keys list \
          -g ${{ env.AZURE_RESOURCE_GROUP }} \
          -n ${{ env.AZURE_FUNCTION_APP_NAME }} \
          --query functionKeys.default -o tsv)

        updated=$(az apim nv update \
          -g ${{ env.AZURE_RESOURCE_GROUP }} \
          -n ${{ env.AZURE_APIM_NAME }} \
          --named-value-id "X_FUNCTIONS_KEY_MMS" \
          --value $functionKey)

  deploy-prod:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    name: Deploy to Prod

    needs:
    - deploy-dev

    runs-on: ubuntu-latest

    environment: prod

    env:
      AZURE_RESOURCE_GROUP: "rg-${{ vars.AZURE_ENV_NAME }}-${{ vars.AZURE_ENV_INFRA }}-${{ vars.AZURE_LOCATION_CODE }}"
      AZURE_APIM_NAME: "apim-${{ vars.AZURE_ENV_NAME }}-${{ vars.AZURE_ENV_INFRA }}-${{ vars.AZURE_LOCATION_CODE }}"
      AZURE_FUNCTION_APP_NAME: "fncapp-${{ vars.AZURE_ENV_NAME }}-md2html-${{ vars.AZURE_ENV_INFRA }}-${{ vars.AZURE_LOCATION_CODE }}"

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: nt-mms
        path: artifact/nt-mms

    - name: Zip artifact
      shell: bash
      run: |
        pushd artifact/nt-mms
        zip -r fncapp.zip .
        popd

        mv artifact/nt-mms/fncapp.zip artifact/fncapp.zip

    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ env.AZURE_CLIENT_ID }}
        tenant-id: ${{ env.AZURE_TENANT_ID }}
        subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}        

    - name: Deploy artifact
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_FUNCTION_APP_NAME }}
        package: artifact/fncapp.zip

    - name: Update APIM named value with function key
      shell: bash
      run: |
        functionKey=$(az functionapp keys list \
          -g ${{ env.AZURE_RESOURCE_GROUP }} \
          -n ${{ env.AZURE_FUNCTION_APP_NAME }} \
          --query functionKeys.default -o tsv)

        updated=$(az apim nv update \
          -g ${{ env.AZURE_RESOURCE_GROUP }} \
          -n ${{ env.AZURE_APIM_NAME }} \
          --named-value-id "X_FUNCTIONS_KEY_MMS" \
          --value $functionKey)
